Repository executablebooks/MyST-NB, pull requests merged in 2024-09, with the labels that each got.

#615 Update glueing docs for NumPy >=2.0
  docs/render/glue.md
Labels: documentation

#604 Fix incorrect output from prints originating from different processes
  myst_nb/core/utils.py
  tests/notebooks/merge_streams_parallel.ipynb
  tests/test_render_outputs.py
  tests/test_render_outputs/test_merge_streams_parallel.xml
Labels: bug

#634 MAINT: removing version pinnings for testing and rtd
  docs/authoring/text-notebooks.md
  docs/requirements.txt
  pyproject.toml
  tox.ini
Labels: dependencies
