Repository executablebooks/MyST-NB, pull requests merged in 2024-11, with the labels that each got.

#639 CI: adding devdeps testing and cron and workflow dispatch
  .github/workflows/tests.yml
  .github/workflows/tests_devdeps.yml
  tox.ini
Labels: testing

#641 FIX: fix path suffix condition in core/read.py
  myst_nb/core/read.py
  tests/conftest.py
  tests/notebooks/custom-formats2.extra.exnt
  tests/test_execute.py
  tests/test_execute/test_custom_convert_multiple_extensions_auto.ipynb
  tests/test_execute/test_custom_convert_multiple_extensions_auto.xml
  tests/test_execute/test_custom_convert_multiple_extensions_cache.ipynb
  tests/test_execute/test_custom_convert_multiple_extensions_cache.xml
Labels: bug

#600 ENH: Support translated notebooks
  myst_nb/sphinx_.py
  tests/conftest.py
  tests/notebooks/basic_run_intl.ipynb
  tests/notebooks/locale/es/LC_MESSAGES/basic_run_intl.po
  tests/test_parser.py
  tests/test_parser/test_basic_run_intl.xml
Labels: enhancement
