Repository executablebooks/MyST-NB, pull requests merged in 2025-04, with the labels that each got.

#669 MAINT: minor cleanups
  .github/release.yml
  docs/requirements.txt
Labels: maintanence

#454 ENH: Adding scroll bars with proper cell tags
  myst_nb/static/mystnb.css
Labels: enhancement

#656 Use admonitions to style collapsible cells :)
  myst_nb/sphinx_.py
  myst_nb/static/mystnb.css
Labels: bug
