Repository executablebooks/MyST-NB, pull requests merged in 2025-02, with the labels that each got.

#657 add `configuration` key to readthedocs.yml
  .readthedocs.yml
Labels: testing, upstream

#659 MAINT: fix CI in prep for release
  .github/workflows/tests.yml
Labels: testing

#665 DOCS: clarify meaning of merge_streams option (#664)
  docs/render/format_code_cells.md
  myst_nb/core/config.py
Labels: documentation
